# Site settings
title: Stefan Reinprecht | Interdisciplinary Designer
email: hello@stefanreinprecht.at
description: > # The Portfolio-Site of Stefan Reinprecht.
  I make Films and Websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stefanreinprecht.at" # the base hostname & protocol for your site
twitter_username: reinpal
github_username:  reinpal
behance_username:  StefanReinprecht
vimeo_username:  stefanreinprecht
facebook_username:  stefan.reinprecht
youtube_username: stefanreinprecht

highlighter: pygments

defaults:
  -
    scope:
      path: ""
    values:
      author: "Stefan Reinprecht"

# Build settings
markdown: kramdown

sass:
  sass_dir: scss

gems:
  - jekyll-sitemap

exclude: [
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  README.md
]