# Site settings
title: Stefan Reinprecht
email: hello@stefanreinprecht.at
description: > # The Portfolio-Site of Stefan Reinprecht. 
  I make Websites and Films. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: reinpal
github_username:  reinpal
behance_username:  StefanReinprecht
vimeo_username:  reini12
facebook_username:  stefan.reinprecht
youtube_username: Reinolds12

highlighter: pygments

defaults:
  -
    scope:
      path: ""
    values:
      author: "Stefan Reinprecht"

# Build settings
markdown: kramdown

sass:
  sass_dir: scss

exclude: [
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  README.md
]